/**
 * Agent API contract tests.
 *
 * These validate that route handlers return response shapes matching
 * the runtime OpenAPI spec generated by `@hono/zod-openapi` from
 * `createRoute(...)` definitions in `routes/agent/index.ts` and served
 * at `/api/v1/agent/openapi.json`. They use the Hono test client
 * (app.request) and mock the database layer to avoid needing a running
 * database.
 *
 * The middleware validates pre-shared tokens by querying the agents table.
 * We mock the DB to return a valid agent for our test token.
 */
import { agentHeartbeatResponseSchema } from '@hashhive/shared'
import { describe, expect, it, mock } from 'bun:test'

// Mock the DB so requireAgentToken middleware can resolve the pre-shared token.
// Service modules (tasks, campaigns, events) are also mocked to prevent real
// modules from entering bun's shared module cache, which would break mock
// isolation for other test files (e.g., campaign-transition.test.ts).
const TEST_AGENT_TOKEN = 'test-agent-preshared-token'

// Snake_case row kept as a reference for building the camelCase mock below.
// The actual snake→camelCase mapping is validated in tasks.test.ts.
const mockSnakeCaseTaskRow = {
  id: 42,
  attack_id: 7,
  campaign_id: 3,
  agent_id: 1,
  status: 'assigned',
  work_range: { start: 0, end: 10000000 },
  progress: {},
  result_stats: {},
  required_capabilities: {},
  assigned_at: '2026-03-24T00:00:00.000Z',
  started_at: null,
  completed_at: null,
  failure_reason: null,
  retry_count: 0,
  created_at: '2026-03-24T00:00:00.000Z',
  updated_at: '2026-03-24T00:00:00.000Z',
}

const mockAgent = {
  id: 1,
  projectId: 1,
  status: 'online',
  capabilities: {},
}

const mockSelect = mock(() => ({
  from: mock(() => ({
    where: mock(() => ({
      limit: mock(() => Promise.resolve([mockAgent])),
    })),
  })),
}))

const mockExecute = mock(() => Promise.resolve([mockSnakeCaseTaskRow]))

// Pull the real pure helpers in BEFORE mock.module runs so the mock
// factory can re-export them. `mock.module` is process-global in
// bun:test; without this re-export, `agents-service.test.ts` (which
// imports these symbols) gets `undefined` for them when its file is
// loaded *after* this one — a Linux/macOS-load-order CI flake. See
// GOTCHAS.md "Re-export the real implementation when you must mock
// siblings" and the crackers-routes.test.ts precedent.
import {
  classifyRecentErrors as realClassifyRecentErrors,
  classifyWorstSeverity as realClassifyWorstSeverity,
  decideHeartbeatTransition as realDecideHeartbeatTransition,
  pickCurrentTaskByAgent as realPickCurrentTaskByAgent,
  scrubAgentErrorContext as realScrubAgentErrorContext,
} from '../../src/services/agents.js'

// Service type imports for satisfies-pinning per the contract-test
// mocks convention. Each fixture below is constrained against
// `Awaited<ReturnType<typeof svc>>` so a signature drift in the
// service surfaces as a type-check failure here.
type AgentsHeartbeatService = typeof import('../../src/services/agents/heartbeat.js')
type ProcessHeartbeatResult = Awaited<ReturnType<AgentsHeartbeatService['processHeartbeat']>>

// processHeartbeat real return is `{agent: Agent|null, hasHighPriorityTasks,
// taskFailureSummary?}`. The route only reads `hasHighPriorityTasks`, but
// the pin catches any future widening that the route would then consume.
// Use `satisfies` rather than a type annotation so the fixture's literal
// types aren't widened to the service's return-type union (the convention's
// "Do NOT use explicit type annotations on the fixture" anti-pattern).
const processHeartbeatFixture = {
  agent: null,
  hasHighPriorityTasks: false,
} satisfies ProcessHeartbeatResult

mock.module('../../src/services/agents.js', () => ({
  processHeartbeat: mock(() => Promise.resolve(processHeartbeatFixture)),
  logAgentError: mock(() => Promise.resolve()),
  // Real impls re-exported so sibling tests see the genuine functions
  // regardless of which file bun loads first.
  classifyRecentErrors: realClassifyRecentErrors,
  classifyWorstSeverity: realClassifyWorstSeverity,
  decideHeartbeatTransition: realDecideHeartbeatTransition,
  pickCurrentTaskByAgent: realPickCurrentTaskByAgent,
  scrubAgentErrorContext: realScrubAgentErrorContext,
}))

// Mock events and tasks to prevent real modules from entering the shared bun
// module cache (which leaks across test files via mock.module merge behavior).
// campaigns.js is NOT mocked here — its mock.module overrides leak into other
// files' real campaigns.js via ESM export merging, replacing resolveGenerationStrategy.
// Partial mock: only what this test file needs. Listing every export
// here would replace the real `emit` / `broadcastSystemEvent` process-
// wide, breaking events.test.ts on Linux (where load order makes this
// file run before events.test.ts). Per GOTCHAS.md "Shared module cache":
// `mock.module` merges into the namespace — non-mocked exports pass
// through to the real module.
mock.module('../../src/services/events.js', () => ({
  emitCrackResult: mock(),
  emitTaskUpdate: mock(),
  emitCampaignStatus: mock(),
  emitResourceUpdate: mock(),
}))

// Mock tasks.js so the real module is never cached — the snake_case→camelCase
// mapping is validated in tasks.test.ts; here we only test the route contract.
// This also removes the need to mock campaigns.js (which tasks.js imported).
const mockCamelCaseTask = {
  id: mockSnakeCaseTaskRow.id,
  attackId: mockSnakeCaseTaskRow.attack_id,
  campaignId: mockSnakeCaseTaskRow.campaign_id,
  agentId: mockSnakeCaseTaskRow.agent_id,
  status: mockSnakeCaseTaskRow.status,
  workRange: mockSnakeCaseTaskRow.work_range,
  progress: mockSnakeCaseTaskRow.progress,
  resultStats: mockSnakeCaseTaskRow.result_stats,
  requiredCapabilities: mockSnakeCaseTaskRow.required_capabilities,
  assignedAt: mockSnakeCaseTaskRow.assigned_at,
  startedAt: mockSnakeCaseTaskRow.started_at,
  completedAt: mockSnakeCaseTaskRow.completed_at,
  failureReason: mockSnakeCaseTaskRow.failure_reason,
  retryCount: mockSnakeCaseTaskRow.retry_count,
  createdAt: mockSnakeCaseTaskRow.created_at,
  updatedAt: mockSnakeCaseTaskRow.updated_at,
}

// Pull the real pure helpers in BEFORE mock.module runs so the mock
// factory can re-export them. Without re-export, `agents-service.test.ts`
// would receive our stubs instead of the genuine implementations for
// any file bun loads after this one — the same Linux/macOS-load-order
// CI flake documented in GOTCHAS.md "Re-export the real implementation
// when you must mock siblings."
import {
  AGENT_TASK_ACTIVE_STATUSES as realAgentTaskActiveStatuses,
  projectAgentTaskRows as realProjectAgentTaskRows,
} from '../../src/services/tasks.js'

// Mock tasks.js so the real module is never cached — the snake_case→camelCase
// mapping is validated in tasks.test.ts; here we only test the route contract.
// This also removes the need to mock campaigns.js (which tasks.js imported).
//
// Each fixture below is pinned via `satisfies Awaited<ReturnType<typeof svc>>`
// per the contract-test mocks convention. The convention's first applied
// use was the ZapResponse shape fix in PR #190; these pins close the loop
// by enforcing the constraint statically so a service-side return-type
// change surfaces at type-check rather than as a wire-shape regression.
type TasksService = typeof import('../../src/services/tasks.js')
type TasksRetryService = typeof import('../../src/services/tasks/retry.js')
type TasksZapsService = typeof import('../../src/services/tasks/zaps.js')

// Extract the task-row shape that both updateTaskProgress and
// handleTaskFailure return on the success branch. They share the
// Drizzle `tasks` table .returning() shape; deriving the type from
// the service signature keeps the fixture pinned to the real shape
// without having to import the Drizzle table type directly.
type TaskUpdateSuccess = Extract<
  Awaited<ReturnType<TasksService['updateTaskProgress']>>,
  { task: unknown }
>
type TaskRow = TaskUpdateSuccess['task']

// mockCamelCaseTask is built from mockSnakeCaseTaskRow with all the
// camelCase keys the Drizzle `.returning()` produces. `satisfies`
// constrains the value without widening it: if mockCamelCaseTask's
// keys/types don't satisfy TaskRow, type-check fails here rather
// than at the route boundary. `as` would silently accept divergence.
const taskRowFixture = mockCamelCaseTask satisfies TaskRow

// updateTaskProgress real return is `{task} | {error}`. The route's
// `'error' in result` branch routes to 400; the {task} branch yields
// the 200 ack body. Pin the success branch. `satisfies` keeps the
// literal type narrow (per the convention's annotation anti-pattern).
const updateTaskProgressFixture = {
  task: taskRowFixture,
} satisfies Awaited<ReturnType<TasksService['updateTaskProgress']>>
// handleTaskFailure real return is `{task, retried} | {error}`. Mock
// the success-no-retry branch.
const handleTaskFailureFixture = {
  task: taskRowFixture,
  retried: false,
} satisfies Awaited<ReturnType<TasksRetryService['handleTaskFailure']>>
// getZapsForTask real return is `{zaps, hasMore} | {error}`. PR #190 fixed
// the shape; this pin enforces it stays correct.
const getZapsForTaskFixture = {
  zaps: [],
  hasMore: false,
} satisfies Awaited<ReturnType<TasksZapsService['getZapsForTask']>>

// Sibling mocks pinned via `mock<typeof svc[fnName]>(...)` per the
// contract-test mocks convention's dynamic-return pattern. Bun's
// `mock.module` MERGES — non-mocked exports pass through to the real
// module (per GOTCHAS.md "Shared module cache"). But the real
// `services/tasks.js` pulls in DB / queue modules that this test's
// mock graph can't load cleanly, so any export the route module
// touches needs an explicit mock here to keep the merged namespace
// import-safe. Only assignNextTask + updateTaskProgress +
// handleTaskFailure + getZapsForTask are actually called from the
// agent routes under test; the others are kept-and-pinned to harden
// the namespace and to surface signature drift at construction time.
const listTasksEmpty = {
  tasks: [],
  total: 0,
  limit: 50,
  offset: 0,
} satisfies Awaited<ReturnType<TasksService['listTasks']>>
const reassignStaleEmpty = {
  reassigned: 0,
  rebalanced: 0,
  failedOverrun: 0,
  failedMaxRetries: 0,
  errored: 0,
} satisfies Awaited<ReturnType<TasksRetryService['reassignStaleTasks']>>
// Extracted so a test can override the return for the preemption
// stop-signal path (#97 U4) via `.mockResolvedValueOnce`.
const updateTaskProgressMock = mock<TasksService['updateTaskProgress']>(
  async () => updateTaskProgressFixture
)
mock.module('../../src/services/tasks.js', () => ({
  assignNextTask: mock<TasksService['assignNextTask']>(async () => mockCamelCaseTask),
  updateTaskProgress: updateTaskProgressMock,
  handleTaskFailure: mock<TasksRetryService['handleTaskFailure']>(
    async () => handleTaskFailureFixture
  ),
  generateTasksForAttack: mock<TasksService['generateTasksForAttack']>(async () => ({
    tasks: [],
    count: 0,
  })),
  reassignStaleTasks: mock<TasksRetryService['reassignStaleTasks']>(async () => reassignStaleEmpty),
  getTaskById: mock<TasksService['getTaskById']>(async () => null),
  listTasks: mock<TasksService['listTasks']>(async () => listTasksEmpty),
  getZapsForTask: mock<TasksZapsService['getZapsForTask']>(async () => getZapsForTaskFixture),
  // Re-export real impls so sibling tests see the genuine functions.
  AGENT_TASK_ACTIVE_STATUSES: realAgentTaskActiveStatuses,
  projectAgentTaskRows: realProjectAgentTaskRows,
}))

// Preemption stop-signal source (#97 U4). The heartbeat handler calls
// getStopTaskIdsForAgent; the real impl's `.where()`-terminal query does not
// fit this file's `.limit()`-only db mock, so pin it. Default empty so
// existing heartbeat assertions (stopTaskIds omitted) hold; override per-test.
const getStopTaskIdsForAgentMock = mock<() => Promise<number[]>>(async () => [])
mock.module('../../src/services/tasks/preemption.js', () => ({
  getStopTaskIdsForAgent: getStopTaskIdsForAgentMock,
}))

// Pull the real pure helpers in BEFORE mock.module runs for crackers.js
// so the mock factory can re-export them. Without this, sibling tests
// (crackers-routes.test.ts and any compareCrackerVersions unit suite)
// would receive our stubs instead of the genuine impls — process-global
// mock.module merge per GOTCHAS.md "Re-export the real implementation
// when you must mock siblings."
import {
  compareCrackerVersions as realCompareCrackerVersions,
  isKnownEngine as realIsKnownEngine,
  normalizeEngineName as realNormalizeEngineName,
} from '../../src/services/crackers.js'

// Mock resources.js and crackers.js so the /resources and /cracker routes
// have reachable rejection paths in the contract test. The real modules
// touch the DB and object store; here we only validate the wire envelope
// and exercise the route-level catch with mockImplementationOnce.
mock.module('../../src/services/resources.js', () => ({
  getAgentDownloadUrl: mock(() =>
    Promise.resolve({ url: 'https://example.test/object', expiresIn: 600 })
  ),
}))

mock.module('../../src/services/crackers.js', () => ({
  // DB-touching surfaces get stubbed; pure helpers are re-exported real.
  getLatestCracker: mock(() => Promise.resolve(null)),
  getCrackerDownloadUrl: mock(() =>
    Promise.resolve({ url: 'https://example.test/cracker', expiresIn: 600 })
  ),
  compareCrackerVersions: realCompareCrackerVersions,
  isKnownEngine: realIsKnownEngine,
  normalizeEngineName: realNormalizeEngineName,
}))

mock.module('../../src/db/index.js', () => ({
  db: {
    select: mockSelect,
    execute: mockExecute,
  },
  client: {},
}))

// Mock the logger so route-layer log-shape assertions (the hasError
// branch on /heartbeat's failure-path log, and similar structured logs
// on other agent routes) can verify their argument shape without
// scraping stdout. Mirrors the integration test's pattern in
// tests/integration/agent-heartbeat.test.ts.
const loggerMock = {
  info: mock(),
  warn: mock(),
  error: mock(),
  debug: mock(),
}

mock.module('../../src/config/logger.js', () => ({
  logger: loggerMock,
}))

import { app } from '../../src/index.js'
import { agentToken } from '../fixtures.js'

const AGENT_BASE = '/api/v1/agent'

/**
 * Assert the documented Agent API validation-error envelope
 * (`{error: {code: 'VALIDATION_ERROR', message}}`). This is the contract
 * shape the agent surface's `defaultHook` (in `openapi/components.ts`
 * as `agentOpenApiHonoOptions.defaultHook`) produces; testing for it
 * (rather than the bare 400) catches regressions where the hook is
 * dropped and `@hono/zod-openapi`'s built-in default falls back to its
 * `{success, error: ZodError}` body shape.
 */
async function expectAgentValidationError(res: Response): Promise<void> {
  const body = (await res.json()) as Record<string, unknown>
  expect(body).toHaveProperty('error')
  const err = body['error'] as Record<string, unknown>
  expect(err['code']).toBe('VALIDATION_ERROR')
  expect(typeof err['message']).toBe('string')
}

// ─── POST /sessions — removed (should 404) ──────────────────────────

describe('Agent API: POST /sessions (removed)', () => {
  it('should return 404 since session endpoint no longer exists', async () => {
    const res = await app.request(`${AGENT_BASE}/sessions`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ token: 'some-token' }),
    })

    expect(res.status).toBe(404)
  })
})

// ─── POST /heartbeat — Agent Heartbeat ──────────────────────────────

describe('Agent API: POST /heartbeat', () => {
  it('should return 401 without auth token', async () => {
    const res = await app.request(`${AGENT_BASE}/heartbeat`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ status: 'online' }),
    })

    expect(res.status).toBe(401)
    const body = await res.json()
    expect(body['error']).toBeDefined()
    expect(body['error']['code']).toBe('AUTH_TOKEN_INVALID')
  })

  it('should return 400 for invalid heartbeat status enum', async () => {
    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/heartbeat`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ status: 'invalid-status' }),
    })

    expect(res.status).toBe(400)
  })

  it('accepts a legacy heartbeat with status only (back-compat baseline)', async () => {
    // Arrange — locks in lenient policy. Existing agents in the wild
    // still post `{status: 'online'}` and nothing else; tightening the
    // schema (e.g., adding .strict()) would silently break them.
    const token = agentToken(TEST_AGENT_TOKEN)

    // Act
    const res = await app.request(`${AGENT_BASE}/heartbeat`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ status: 'online' }),
    })

    // Assert
    expect(res.status).toBe(200)
    const body = (await res.json()) as Record<string, unknown>
    expect(body['acknowledged']).toBe(true)
    // Pin the omit-when-no-priority-work policy at the contract level.
    // The integration suite mirrors this in
    // `tests/integration/agent-heartbeat.test.ts` (the `.toBeUndefined()`
    // cases on the error-status / empty-hashModes / null-capabilities
    // paths inside the heartbeat-error-handling describe block).
    // Asserting it here keeps a regression where the route emits `false`
    // from slipping past the unit contract test before reaching the
    // integration layer.
    expect(body['hasHighPriorityTasks']).toBeUndefined()
    // Omit-when-empty for the preemption stop-signal too (#97 U4).
    expect(body['stopTaskIds']).toBeUndefined()
    // Contract proof: the response body satisfies the shared Zod schema.
    // The runtime OpenAPI spec at /api/v1/agent/openapi.json is generated
    // from the same schema (bound via createRoute in routes/agent/index.ts),
    // so parse() success proves the route handler ↔ shared schema pair
    // stays in sync — and by extension the published spec.
    expect(() => agentHeartbeatResponseSchema.parse(body)).not.toThrow()
  })

  it('returns stopTaskIds when the agent has preempted tasks (#97 U4)', async () => {
    // Arrange — the agent has two preempted-paused tasks.
    getStopTaskIdsForAgentMock.mockResolvedValueOnce([42, 43])
    const token = agentToken(TEST_AGENT_TOKEN)

    // Act
    const res = await app.request(`${AGENT_BASE}/heartbeat`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', authorization: `Bearer ${token}` },
      body: JSON.stringify({ status: 'online' }),
    })

    // Assert
    expect(res.status).toBe(200)
    const body = (await res.json()) as Record<string, unknown>
    expect(body['stopTaskIds']).toEqual([42, 43])
    expect(() => agentHeartbeatResponseSchema.parse(body)).not.toThrow()
  })

  it('returns hasHighPriorityTasks=true when service flags high-priority work', async () => {
    // Arrange — override the default mock for this single call so the
    // service reports high-priority work is available. The route is
    // expected to surface the flag verbatim per the heartbeat-response
    // contract documented in
    // `docs/issues/155-task-distribution-assignment-spec.md`.
    const { processHeartbeat } = await import('../../src/services/agents.js')
    ;(
      processHeartbeat as unknown as { mockImplementationOnce: (fn: () => unknown) => void }
    ).mockImplementationOnce(() => Promise.resolve({ hasHighPriorityTasks: true }))

    const token = agentToken(TEST_AGENT_TOKEN)

    // Act
    const res = await app.request(`${AGENT_BASE}/heartbeat`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ status: 'online' }),
    })

    // Assert
    expect(res.status).toBe(200)
    const body = (await res.json()) as Record<string, unknown>
    expect(body['acknowledged']).toBe(true)
    expect(body['hasHighPriorityTasks']).toBe(true)
    // Contract proof against the shared schema (and via mirror, OpenAPI).
    const parsed = agentHeartbeatResponseSchema.parse(body)
    expect(parsed.hasHighPriorityTasks).toBe(true)
  })

  it('returns Agent-shaped envelope with HEARTBEAT_ERROR when processHeartbeat throws', async () => {
    // Arrange — force the service to reject so the route's failure path
    // is exercised. Clear the logger mock first so the call-shape
    // assertion below isn't polluted by any unrelated error log a
    // preceding test in this describe block might have emitted (the
    // sibling test at line 395-430 clears explicitly; mirror that
    // discipline here so the implicit ordering invariant doesn't
    // silently break when a future test is added above this one).
    loggerMock.error.mockClear()
    // The negative-shape assertions on `timestamp` and
    // `requestId` discriminate the Agent envelope from the dashboard
    // envelope emitted by the global `app.onError`; without them a
    // regression that falls through to the global handler could still
    // satisfy `error.code === 'HEARTBEAT_ERROR'` by accident.
    const { processHeartbeat } = await import('../../src/services/agents.js')
    ;(
      processHeartbeat as unknown as { mockImplementationOnce: (fn: () => unknown) => void }
    ).mockImplementationOnce(() => Promise.reject(new Error('db down')))

    const token = agentToken(TEST_AGENT_TOKEN)

    // Act
    const res = await app.request(`${AGENT_BASE}/heartbeat`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ status: 'online' }),
    })

    // Assert
    expect(res.status).toBe(500)
    const body = (await res.json()) as { error: Record<string, unknown> }
    expect(body.error.code).toBe('HEARTBEAT_ERROR')
    // Pin to the literal message. A regression that switches the wire
    // message to `err.message` (e.g., 'db down') would leak internal
    // diagnostic detail to agents; asserting the static string blocks
    // that class of change.
    expect(body.error.message).toBe('Failed to process heartbeat')
    // Negative shape: the Agent envelope omits `timestamp` and
    // `requestId`. Their presence would mean we fell through to the
    // dashboard envelope at `app.onError`.
    expect(body.error['timestamp']).toBeUndefined()
    expect(body.error['requestId']).toBeUndefined()
    // Log shape: the route logs the four documented keys (err, agentId,
    // status, hasError). No error payload was posted so hasError stays
    // false; the hasError=true branch is pinned by the next test.
    const heartbeatErrorLogs = loggerMock.error.mock.calls.filter((call) => {
      const arg = call[0] as Record<string, unknown> | undefined
      return arg?.['err'] !== undefined && arg?.['agentId'] === 1
    })
    expect(heartbeatErrorLogs).toHaveLength(1)
    const logCtx = heartbeatErrorLogs[0]?.[0] as Record<string, unknown>
    expect(logCtx['status']).toBe('online')
    expect(logCtx['hasError']).toBe(false)
  })

  it('logs hasError=true when heartbeat carries an error payload and processHeartbeat throws', async () => {
    // Arrange — pin the second branch of the route's failure-path log
    // (`hasError: Boolean(data.error)`). Without this test a regression
    // that always logs `hasError: false` would land green.
    loggerMock.error.mockClear()
    const { processHeartbeat } = await import('../../src/services/agents.js')
    ;(
      processHeartbeat as unknown as { mockImplementationOnce: (fn: () => unknown) => void }
    ).mockImplementationOnce(() => Promise.reject(new Error('db down')))

    const token = agentToken(TEST_AGENT_TOKEN)

    // Act
    const res = await app.request(`${AGENT_BASE}/heartbeat`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({
        status: 'error',
        error: { severity: 'fatal', message: 'gpu hung' },
      }),
    })

    // Assert
    expect(res.status).toBe(500)
    const heartbeatErrorLogs = loggerMock.error.mock.calls.filter((call) => {
      const arg = call[0] as Record<string, unknown> | undefined
      return arg?.['err'] !== undefined && arg?.['agentId'] === 1
    })
    expect(heartbeatErrorLogs).toHaveLength(1)
    const logCtx = heartbeatErrorLogs[0]?.[0] as Record<string, unknown>
    expect(logCtx['status']).toBe('error')
    expect(logCtx['hasError']).toBe(true)
  })

  it('accepts a heartbeat with currentTask and warning error', async () => {
    // Arrange
    const token = agentToken(TEST_AGENT_TOKEN)

    // Act
    const res = await app.request(`${AGENT_BASE}/heartbeat`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({
        status: 'online',
        currentTask: {
          taskId: 42,
          progress: 0.5,
          speed: 12345,
          temperature: 72,
        },
        error: {
          severity: 'warning',
          message: 'temperature spike',
          context: { gpuId: 0 },
        },
      }),
    })

    // Assert
    expect(res.status).toBe(200)
    const body = (await res.json()) as Record<string, unknown>
    expect(body['acknowledged']).toBe(true)
  })

  it('accepts a heartbeat with a fatal error and no currentTask', async () => {
    // Arrange
    const token = agentToken(TEST_AGENT_TOKEN)

    // Act
    const res = await app.request(`${AGENT_BASE}/heartbeat`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({
        status: 'error',
        error: { severity: 'fatal', message: 'hashcat crashed' },
      }),
    })

    // Assert
    expect(res.status).toBe(200)
    const body = (await res.json()) as Record<string, unknown>
    expect(body['acknowledged']).toBe(true)
  })

  it('rejects an error.severity outside the warning|fatal enum', async () => {
    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/heartbeat`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({
        status: 'online',
        error: { severity: 'info', message: 'just a note' },
      }),
    })
    expect(res.status).toBe(400)
    await expectAgentValidationError(res)
  })

  it('rejects an empty error.message', async () => {
    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/heartbeat`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({
        status: 'online',
        error: { severity: 'warning', message: '' },
      }),
    })
    expect(res.status).toBe(400)
    await expectAgentValidationError(res)
  })

  it('rejects a non-positive currentTask.taskId', async () => {
    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/heartbeat`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({
        status: 'online',
        currentTask: { taskId: 0, progress: 0, speed: 0 },
      }),
    })
    expect(res.status).toBe(400)
    await expectAgentValidationError(res)
  })

  it('rejects a negative currentTask.progress', async () => {
    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/heartbeat`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({
        status: 'online',
        currentTask: { taskId: 42, progress: -0.1, speed: 0 },
      }),
    })
    expect(res.status).toBe(400)
    await expectAgentValidationError(res)
  })

  // ─── Size-cap boundaries on error.message and error.context ─────────
  // These guard the DoS-bound `.max(4096)` and `.refine()` 16K-char cap
  // on the heartbeat error block. A refactor that drops either would
  // ship silently without these tests.

  it('accepts an error.message at the 4096-character cap', async () => {
    // Arrange
    const token = agentToken(TEST_AGENT_TOKEN)
    const messageAtCap = 'a'.repeat(4096)

    // Act
    const res = await app.request(`${AGENT_BASE}/heartbeat`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({
        status: 'online',
        error: { severity: 'warning', message: messageAtCap },
      }),
    })

    // Assert
    expect(res.status).toBe(200)
  })

  it('rejects an error.message that exceeds the 4096-character cap', async () => {
    // Arrange
    const token = agentToken(TEST_AGENT_TOKEN)
    const messageOverCap = 'a'.repeat(4097)

    // Act
    const res = await app.request(`${AGENT_BASE}/heartbeat`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({
        status: 'online',
        error: { severity: 'warning', message: messageOverCap },
      }),
    })

    // Assert
    expect(res.status).toBe(400)
    await expectAgentValidationError(res)
  })

  it('rejects an error.context whose JSON serialization exceeds 16K characters', async () => {
    // Arrange — a single string value just past the 16K-char limit so
    // `JSON.stringify(context).length` exceeds HEARTBEAT_ERROR_CONTEXT_MAX_CHARS.
    const token = agentToken(TEST_AGENT_TOKEN)
    const oversized = { blob: 'x'.repeat(16 * 1024 + 1) }

    // Act
    const res = await app.request(`${AGENT_BASE}/heartbeat`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({
        status: 'online',
        error: { severity: 'warning', message: 'big', context: oversized },
      }),
    })

    // Assert
    expect(res.status).toBe(400)
    await expectAgentValidationError(res)
  })

  // ─── Recovery from status='error' via heartbeat ─────────────────────
  // The heartbeat endpoint uses requireAgentTokenForHeartbeatRecovery so an
  // agent whose row was forced to status='error' by a prior fatal
  // heartbeat can post a clean heartbeat to come back online. Every
  // other agent endpoint stays strict (rejects error-state agents).

  it('allows an errored agent to post a recovery heartbeat', async () => {
    // Arrange — simulate an agent that was previously forced to
    // status='error' by a fatal heartbeat. The strict middleware would
    // reject this token; the recovery variant on /heartbeat admits it
    // so processHeartbeat can transition it back to 'online'.
    const token = agentToken(TEST_AGENT_TOKEN)
    const priorStatus = mockAgent.status
    mockAgent.status = 'error'

    try {
      // Act
      const res = await app.request(`${AGENT_BASE}/heartbeat`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ status: 'online' }),
      })

      // Assert — the middleware admits the errored agent (200, not 401)
      // and the handler acknowledges.
      expect(res.status).toBe(200)
      const body = (await res.json()) as Record<string, unknown>
      expect(body['acknowledged']).toBe(true)
    } finally {
      mockAgent.status = priorStatus
    }
  })

  it('still rejects errored agents on work endpoints (strict middleware)', async () => {
    // Arrange — same errored row, but posting to /tasks/next (which
    // uses the strict requireAgentToken middleware). Confirms the
    // recovery exemption is heartbeat-only.
    const token = agentToken(TEST_AGENT_TOKEN)
    const priorStatus = mockAgent.status
    mockAgent.status = 'error'

    try {
      // Act
      const res = await app.request(`${AGENT_BASE}/tasks/next`, {
        method: 'POST',
        headers: { authorization: `Bearer ${token}` },
      })

      // Assert
      expect(res.status).toBe(401)
      const body = (await res.json()) as Record<string, unknown>
      expect((body['error'] as Record<string, unknown>)['code']).toBe('AUTH_TOKEN_INVALID')
    } finally {
      mockAgent.status = priorStatus
    }
  })
})

// ─── POST /tasks/next — Request Next Task ───────────────────────────

describe('Agent API: POST /tasks/next', () => {
  it('should return 401 without auth token', async () => {
    const res = await app.request(`${AGENT_BASE}/tasks/next`, {
      method: 'POST',
    })

    expect(res.status).toBe(401)
    const body = await res.json()
    expect(body['error']).toBeDefined()
  })

  it('returns camelCase task descriptor when task is available', async () => {
    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/tasks/next`, {
      method: 'POST',
      headers: {
        authorization: `Bearer ${token}`,
      },
    })

    expect(res.status).toBe(200)
    const body = (await res.json()) as Record<string, unknown>
    const task = body['task'] as Record<string, unknown>

    // Task should be present
    expect(task).not.toBeNull()

    // camelCase keys should be defined
    expect(task['attackId']).toBeDefined()
    expect(task['campaignId']).toBeDefined()
    expect(task['workRange']).toBeDefined()

    // retryCount is part of the documented TaskDescriptor contract and
    // is always present (backed by a NOT NULL DEFAULT 0 column). Assert
    // the field is exposed with the expected value so generated agent
    // clients can rely on it.
    expect(task).toHaveProperty('retryCount')
    expect(task['retryCount']).toBe(mockSnakeCaseTaskRow.retry_count)

    // snake_case keys should be absent
    expect(task['attack_id']).toBeUndefined()
    expect(task['campaign_id']).toBeUndefined()
    expect(task['work_range']).toBeUndefined()
    expect(task['retry_count']).toBeUndefined()
  })

  it('round-trips a non-zero retryCount through the snake↔camel projection', async () => {
    // toHaveProperty passes even on an explicit undefined; assert a real
    // non-zero value so a regression that drops the column projection is
    // caught here rather than at runtime in the agent client.
    const tasksMod = await import('../../src/services/tasks.js')
    const assignNextTaskMock = tasksMod.assignNextTask as unknown as ReturnType<typeof mock>
    assignNextTaskMock.mockImplementationOnce(() =>
      Promise.resolve({ ...mockCamelCaseTask, retryCount: 2 })
    )

    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/tasks/next`, {
      method: 'POST',
      headers: { authorization: `Bearer ${token}` },
    })

    expect(res.status).toBe(200)
    const body = (await res.json()) as Record<string, unknown>
    const task = body['task'] as Record<string, unknown>
    expect(task['retryCount']).toBe(2)
    expect(task['retryCount']).not.toBeUndefined()
  })
})

// ─── POST /tasks/:id/report — Report Task Progress ─────────────────

describe('Agent API: POST /tasks/:id/report', () => {
  it('should return 401 without auth token', async () => {
    const res = await app.request(`${AGENT_BASE}/tasks/1/report`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ status: 'running' }),
    })

    expect(res.status).toBe(401)
  })

  it('should return 400 for invalid status enum', async () => {
    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/tasks/1/report`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ status: 'not-a-valid-status' }),
    })

    expect(res.status).toBe(400)
  })
})

// ─── POST /errors — Report Agent Error ──────────────────────────────

describe('Agent API: POST /errors', () => {
  it('should return 401 without auth token', async () => {
    const res = await app.request(`${AGENT_BASE}/errors`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ severity: 'error', message: 'test error' }),
    })

    expect(res.status).toBe(401)
  })

  it('should return 400 for missing required fields', async () => {
    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/errors`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({}),
    })

    expect(res.status).toBe(400)
  })

  it('should return 400 for invalid severity enum', async () => {
    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/errors`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ severity: 'invalid', message: 'test' }),
    })

    expect(res.status).toBe(400)
  })
})

// ─── Failure-path envelope contract across all wrapped agent routes ──
//
// Every agent route now wraps its primary service call in try/catch and
// returns the Agent envelope `{ error: { code, message } }` at HTTP 500
// instead of falling through to the global `app.onError` (which would
// emit the dashboard envelope). These tests pin each route's coarse
// code value AND assert the negative envelope shape — the same
// regression guard already in place for HEARTBEAT_ERROR.

/**
 * Verify that the response is the Agent envelope at HTTP 500 with the
 * expected coarse code. `timestamp`/`requestId` MUST be absent;
 * presence means we fell through to the dashboard envelope at
 * `app.onError`.
 */
async function expectAgentFailureEnvelope(res: Response, expectedCode: string): Promise<void> {
  expect(res.status).toBe(500)
  const body = (await res.json()) as { error: Record<string, unknown> }
  expect(body.error.code).toBe(expectedCode)
  expect(typeof body.error.message).toBe('string')
  expect((body.error.message as string).length).toBeGreaterThan(0)
  expect(body.error['timestamp']).toBeUndefined()
  expect(body.error['requestId']).toBeUndefined()
}

describe('Agent API: failure-path envelope shape', () => {
  it('POST /tasks/next returns TASK_ASSIGN_ERROR when assignNextTask throws', async () => {
    const tasksMod = await import('../../src/services/tasks.js')
    ;(
      tasksMod.assignNextTask as unknown as { mockImplementationOnce: (fn: () => unknown) => void }
    ).mockImplementationOnce(() => Promise.reject(new Error('db down')))

    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/tasks/next`, {
      method: 'POST',
      headers: { authorization: `Bearer ${token}` },
    })

    await expectAgentFailureEnvelope(res, 'TASK_ASSIGN_ERROR')
  })

  it('POST /tasks/:id/report returns TASK_REPORT_ERROR when updateTaskProgress throws', async () => {
    const tasksMod = await import('../../src/services/tasks.js')
    ;(
      tasksMod.updateTaskProgress as unknown as {
        mockImplementationOnce: (fn: () => unknown) => void
      }
    ).mockImplementationOnce(() => Promise.reject(new Error('db down')))

    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/tasks/42/report`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ status: 'running' }),
    })

    await expectAgentFailureEnvelope(res, 'TASK_REPORT_ERROR')
  })

  it('GET /tasks/:id/zaps returns TASK_ZAP_ERROR when getZapsForTask throws', async () => {
    const tasksMod = await import('../../src/services/tasks.js')
    ;(
      tasksMod.getZapsForTask as unknown as { mockImplementationOnce: (fn: () => unknown) => void }
    ).mockImplementationOnce(() => Promise.reject(new Error('db down')))

    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/tasks/42/zaps`, {
      method: 'GET',
      headers: { authorization: `Bearer ${token}` },
    })

    await expectAgentFailureEnvelope(res, 'TASK_ZAP_ERROR')
  })

  it('POST /errors returns ERROR_INGEST_ERROR when logAgentError throws', async () => {
    const agentsMod = await import('../../src/services/agents.js')
    ;(
      agentsMod.logAgentError as unknown as { mockImplementationOnce: (fn: () => unknown) => void }
    ).mockImplementationOnce(() => Promise.reject(new Error('db down')))

    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/errors`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ severity: 'warning', message: 'test' }),
    })

    await expectAgentFailureEnvelope(res, 'ERROR_INGEST_ERROR')
  })

  it('GET /resources/:type/:id/download-url returns RESOURCE_URL_ERROR when getAgentDownloadUrl throws', async () => {
    const resourcesMod = await import('../../src/services/resources.js')
    ;(
      resourcesMod.getAgentDownloadUrl as unknown as {
        mockImplementationOnce: (fn: () => unknown) => void
      }
    ).mockImplementationOnce(() => Promise.reject(new Error('object store down')))

    const token = agentToken(TEST_AGENT_TOKEN)
    // Use the plural form `wordlists` to match the documented OpenAPI
    // example (`resourceParamSchema.openapi({ example: 'wordlists' })`).
    // The route accepts any string for `type`, so the test would pass
    // either way — but probing the documented path keeps the smoke
    // honest about what a regenerated client would actually call.
    const res = await app.request(`${AGENT_BASE}/resources/wordlists/1/download-url`, {
      method: 'GET',
      headers: { authorization: `Bearer ${token}` },
    })

    await expectAgentFailureEnvelope(res, 'RESOURCE_URL_ERROR')
  })

  it('POST /cracker/check-update returns CRACKER_UPDATE_ERROR when getLatestCracker throws', async () => {
    const crackersMod = await import('../../src/services/crackers.js')
    ;(
      crackersMod.getLatestCracker as unknown as {
        mockImplementationOnce: (fn: () => unknown) => void
      }
    ).mockImplementationOnce(() => Promise.reject(new Error('db down')))

    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/cracker/check-update`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ engine: 'hashcat', platform: 'linux-x86_64', version: '6.2.7' }),
    })

    await expectAgentFailureEnvelope(res, 'CRACKER_UPDATE_ERROR')
  })
})

// ─── GET /openapi.json — anonymous spec endpoint (U6) ───────────────
//
// The route-as-spec migration added `/api/v1/agent/openapi.json` as
// the new authoritative spec source. The endpoint MUST be reachable
// without a bearer token (codegen tools and Swagger UI consume it
// anonymously) and the body MUST be a valid OpenAPI 3.1 document.
// A regression that mounted the spec endpoint after `requireAgentToken`
// would turn it 401 and break every downstream client — this suite is
// the guard.

describe('Agent API: GET /openapi.json (route-as-spec)', () => {
  it('returns 200 without a bearer token (anonymous fetch contract)', async () => {
    const res = await app.request(`${AGENT_BASE}/openapi.json`, { method: 'GET' })
    expect(res.status).toBe(200)
  })

  it('returns a valid OpenAPI 3.1 document with the documented surface paths', async () => {
    const res = await app.request(`${AGENT_BASE}/openapi.json`, { method: 'GET' })
    const doc = (await res.json()) as Record<string, unknown>

    expect(doc['openapi']).toBe('3.1.0')
    expect(doc).toHaveProperty('info')
    expect(doc).toHaveProperty('paths')

    const paths = doc['paths'] as Record<string, unknown>
    // Pin the agent surface's documented endpoints — a path silently
    // disappearing from the spec (e.g., because a future refactor
    // dropped `router.openapi(route, handler)` for `router.post(...)`)
    // would be invisible without this assertion.
    expect(paths).toHaveProperty('/heartbeat')
    expect(paths).toHaveProperty('/tasks/next')
    expect(paths).toHaveProperty('/tasks/{taskId}/report')
    expect(paths).toHaveProperty('/tasks/{taskId}/zaps')
    expect(paths).toHaveProperty('/errors')
    expect(paths).toHaveProperty('/benchmark')
    expect(paths).toHaveProperty('/cracker/check-update')
    expect(paths).toHaveProperty('/resources/{type}/{id}/download-url')
  })

  it('declares the AgentBearer security scheme on the spec', async () => {
    const res = await app.request(`${AGENT_BASE}/openapi.json`, { method: 'GET' })
    const doc = (await res.json()) as Record<string, unknown>
    const components = doc['components'] as Record<string, unknown>
    const securitySchemes = components['securitySchemes'] as Record<string, unknown>
    expect(securitySchemes).toHaveProperty('AgentBearer')
  })

  it('emits oneOf with both updateAvailable arms for the cracker check-update response', async () => {
    // The crackerCheckUpdateResponseSchema is a z.discriminatedUnion
    // on `updateAvailable`. The mountCachedSpec call passes
    // `unionPreferredType: 'oneOf'` so the generated spec must emit
    // `oneOf` (not `anyOf`) for the 200 response. A regression that
    // dropped the generator option, or that collapsed the union to a
    // single arm, would silently break generated agent client codegen.
    // We assert the arm count AND the discriminator literal on each
    // arm so a regression that emits `oneOf` of the wrong shape
    // (single-arm, three-arm, or arms keyed on the wrong field) still
    // fails this test.
    const res = await app.request(`${AGENT_BASE}/openapi.json`, { method: 'GET' })
    const doc = (await res.json()) as Record<string, unknown>
    const paths = doc['paths'] as Record<string, unknown>
    const checkUpdate = paths['/cracker/check-update'] as Record<string, unknown>
    const post = checkUpdate['post'] as Record<string, unknown>
    const responses = post['responses'] as Record<string, unknown>
    const ok = responses['200'] as Record<string, unknown>
    const content = ok['content'] as Record<string, unknown>
    const appJson = content['application/json'] as Record<string, unknown>
    const schemaRoot = appJson['schema'] as Record<string, unknown>
    // The schema may be either an inline `oneOf` block or a `$ref` to
    // a component schema (`CrackerCheckUpdateResponse`) which itself
    // declares `oneOf`. Accept both shapes — the wire contract is
    // satisfied as long as the resolved schema is a `oneOf` with two
    // arms keyed on `updateAvailable`.
    const resolvedSchema: Record<string, unknown> = (() => {
      if ('$ref' in schemaRoot) {
        const refPath = (schemaRoot['$ref'] as string).replace('#/components/schemas/', '')
        const components = doc['components'] as Record<string, unknown>
        const schemas = components['schemas'] as Record<string, unknown>
        return schemas[refPath] as Record<string, unknown>
      }
      return schemaRoot
    })()
    expect(resolvedSchema).toHaveProperty('oneOf')
    const arms = resolvedSchema['oneOf'] as Array<Record<string, unknown>>
    expect(arms).toHaveLength(2)
    // Each arm has `properties.updateAvailable.const` (or `.enum`) that
    // pins true / false. Collect the discriminant values and assert
    // both literals are present, in either order.
    const discriminants = arms.map((arm) => {
      const props = arm['properties'] as Record<string, unknown> | undefined
      const ua = props?.['updateAvailable'] as Record<string, unknown> | undefined
      if (ua && 'const' in ua) return ua['const']
      if (ua && Array.isArray(ua['enum'])) return (ua['enum'] as unknown[])[0]
      return undefined
    })
    // Sort via a stable boolean comparator (Array.prototype.sort needs
    // an explicit compare function for non-string values per the lint
    // rule). Asserting via .toContain on each literal would also work
    // but loses the "both arms present, no extras" intent.
    expect([...discriminants].sort((a, b) => (a === b ? 0 : a ? 1 : -1))).toEqual([false, true])
  })
})

// ─── POST /tasks/:id/report — 200 body shape (post-U6 wire contract) ──
//
// U6 introduced a regression where the non-failure success path
// returned `{ acknowledged: true, retried: false }` instead of the
// pre-U6 bare `{ acknowledged: true }`. The fix preserves the original
// shape on the success path and emits `retried` only on the
// failure-retry branch where it carries useful signal. These tests pin
// both shapes against the wire contract so any future regression
// flipping them would fail loudly.

describe('Agent API: POST /tasks/:id/report — 200 body shape', () => {
  it('returns bare { acknowledged: true } on the success path (no `retried` field)', async () => {
    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/tasks/42/report`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ status: 'running' }),
    })

    expect(res.status).toBe(200)
    const body = (await res.json()) as Record<string, unknown>
    expect(body['acknowledged']).toBe(true)
    // Pin the omit-on-success behavior — adding `retried: false` to
    // every ack body would silently break any strict
    // (`disallowUnknownFields`) consumer of the agent contract.
    expect(body['retried']).toBeUndefined()
    // No `action` on the ordinary success path (#97 U4).
    expect(body['action']).toBeUndefined()
  })

  it('returns { acknowledged: true, action: "stop" } when the task was preempted (#97 U4)', async () => {
    // Arrange — updateTaskProgress reports the task is paused (preempted),
    // so the progress write was a no-op and the agent must stop.
    updateTaskProgressMock.mockResolvedValueOnce({ stopped: true })

    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/tasks/42/report`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', authorization: `Bearer ${token}` },
      body: JSON.stringify({ status: 'running' }),
    })

    expect(res.status).toBe(200)
    const body = (await res.json()) as Record<string, unknown>
    expect(body['acknowledged']).toBe(true)
    expect(body['action']).toBe('stop')
  })

  it('returns { acknowledged: true, retried } on the failure-retry branch', async () => {
    // Arrange — force `handleTaskFailure` to report a retry decision.
    const tasksMod = await import('../../src/services/tasks.js')
    ;(
      tasksMod.handleTaskFailure as unknown as {
        mockImplementationOnce: (fn: () => unknown) => void
      }
    ).mockImplementationOnce(() => Promise.resolve({ retried: true }))

    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/tasks/42/report`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ status: 'failed', errors: ['gpu hung'] }),
    })

    expect(res.status).toBe(200)
    const body = (await res.json()) as Record<string, unknown>
    expect(body['acknowledged']).toBe(true)
    expect(body['retried']).toBe(true)
  })

  it('returns action:stop when a failed report targets a preempted task (#97 U6)', async () => {
    // handleTaskFailure reports the task is paused (preempted) — the failure
    // must not un-pause it via the retry branch; the agent is told to stop.
    const tasksMod = await import('../../src/services/tasks.js')
    ;(
      tasksMod.handleTaskFailure as unknown as {
        mockImplementationOnce: (fn: () => unknown) => void
      }
    ).mockImplementationOnce(() => Promise.resolve({ stopped: true }))

    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/tasks/42/report`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', authorization: `Bearer ${token}` },
      body: JSON.stringify({ status: 'failed', errors: ['gpu hung'] }),
    })

    expect(res.status).toBe(200)
    const body = (await res.json()) as Record<string, unknown>
    expect(body['acknowledged']).toBe(true)
    expect(body['action']).toBe('stop')
    expect(body['retried']).toBeUndefined()
  })

  it('rejects non-numeric path param with 400 + VALIDATION_ERROR (zod coerce edge case)', async () => {
    // Arrange — the new `z.coerce.number().int().positive()` schema
    // replaces the old hand-rolled `Number.isNaN || taskId <= 0`
    // guard. Pin the equivalence so a future schema relaxation that
    // dropped `.positive()` or `.int()` would fail loudly.
    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/tasks/abc/report`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ status: 'running' }),
    })

    expect(res.status).toBe(400)
    await expectAgentValidationError(res)
  })

  it('rejects zero path param with 400 + VALIDATION_ERROR (`.positive()` boundary)', async () => {
    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/tasks/0/report`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ status: 'running' }),
    })

    expect(res.status).toBe(400)
    await expectAgentValidationError(res)
  })

  it('rejects path param above PostgreSQL int4 max with 400 + VALIDATION_ERROR', async () => {
    // 2_147_483_648 is MAX_PG_INT4 + 1. Without an upper bound on
    // taskIdParamSchema, this value would coerce successfully through
    // `.coerce.number().int().positive()` and reach the service layer,
    // where the PostgreSQL `serial` column would throw at the DB
    // boundary — surfacing as an opaque 500. The schema's `.max()`
    // boundary keeps the failure mode at the validator (400) where the
    // agent can see a structured envelope and stop polling that ID.
    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/tasks/2147483648/report`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ status: 'running' }),
    })

    expect(res.status).toBe(400)
    await expectAgentValidationError(res)
  })

  it('returns 400 TASK_ERROR when the campaign has no hash list (silent data-loss guard)', async () => {
    // Arrange — force `updateTaskProgress` to return the new
    // `{error}` shape that the service now emits when the agent
    // submits cracked results against a campaign with no
    // `hashListId`. Before this guard, the service logged the
    // condition and fell through to a successful response, which
    // silently dropped the cracked hashes on the floor and let the
    // campaign aggregate tick forward on phantom progress. The
    // route's `'error' in result` branch now surfaces this as a
    // 400 + TASK_ERROR so the agent can quarantine the report
    // instead of marking the task done.
    const tasksMod = await import('../../src/services/tasks.js')
    ;(
      tasksMod.updateTaskProgress as unknown as {
        mockImplementationOnce: (fn: () => unknown) => void
      }
    ).mockImplementationOnce(() =>
      Promise.resolve({
        error:
          'Campaign has no associated hash list; cracked results cannot be stored. Check campaign configuration before resubmitting.',
      })
    )

    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/tasks/42/report`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({
        status: 'completed',
        results: [{ hashValue: 'abc', plaintext: 'def' }],
      }),
    })

    // Assert
    expect(res.status).toBe(400)
    const body = (await res.json()) as { error: Record<string, unknown> }
    expect(body.error.code).toBe('TASK_ERROR')
    // Pin the message verbatim so future service-layer wording
    // changes are caught at the contract layer; agents may surface
    // this string to operators.
    expect(body.error.message).toMatch(/no associated hash list/i)
  })
})

// ─── Errored-agent strict-middleware coverage across work endpoints ──
//
// /heartbeat uses `requireAgentTokenForHeartbeatRecovery` (lenient so
// an errored agent can post a clean heartbeat to recover). Every
// other authenticated route uses the strict `requireAgentToken` which
// rejects agents in `status='error'` with 401 + AUTH_TOKEN_INVALID.
//
// The /tasks/next case is already pinned above; this suite extends
// the same guard across /errors, /benchmark, /resources/*, and
// /cracker/* so a future regression that accidentally swapped the
// middleware on any of them would fail loudly.

/**
 * Assert the documented Agent API auth-invalid envelope
 * (`{error: {code: 'AUTH_TOKEN_INVALID', ...}}` at HTTP 401). A future
 * regression that returned 401 with a different envelope code (e.g.,
 * a new `AUTH_AGENT_ERRORED` discriminator) would land green if we
 * only asserted status code — the envelope code IS the contract for
 * agent client error switching.
 */
async function expectAgentAuthInvalid(res: Response): Promise<void> {
  expect(res.status).toBe(401)
  const body = (await res.json()) as Record<string, unknown>
  expect(body).toHaveProperty('error')
  const err = body['error'] as Record<string, unknown>
  expect(err['code']).toBe('AUTH_TOKEN_INVALID')
  expect(typeof err['message']).toBe('string')
}

describe('Agent API: errored-agent rejection across work endpoints', () => {
  const TEST_AGENT_TOKEN_LOCAL = 'test-agent-preshared-token'
  const errorAgentToken = () => agentToken(TEST_AGENT_TOKEN_LOCAL)

  function withErroredAgent(fn: () => Promise<void>): () => Promise<void> {
    return async () => {
      const priorStatus = mockAgent.status
      mockAgent.status = 'error'
      try {
        await fn()
      } finally {
        mockAgent.status = priorStatus
      }
    }
  }

  it(
    'rejects errored agents on POST /errors',
    withErroredAgent(async () => {
      const res = await app.request(`${AGENT_BASE}/errors`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          authorization: `Bearer ${errorAgentToken()}`,
        },
        body: JSON.stringify({ severity: 'warning', message: 'test' }),
      })
      await expectAgentAuthInvalid(res)
    })
  )

  it(
    'rejects errored agents on POST /benchmark',
    withErroredAgent(async () => {
      const res = await app.request(`${AGENT_BASE}/benchmark`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          authorization: `Bearer ${errorAgentToken()}`,
        },
        body: JSON.stringify({ entries: [] }),
      })
      await expectAgentAuthInvalid(res)
    })
  )

  it(
    'rejects errored agents on GET /resources/:type/:id/download-url',
    withErroredAgent(async () => {
      const res = await app.request(`${AGENT_BASE}/resources/wordlists/1/download-url`, {
        method: 'GET',
        headers: { authorization: `Bearer ${errorAgentToken()}` },
      })
      await expectAgentAuthInvalid(res)
    })
  )

  it(
    'rejects errored agents on POST /cracker/check-update',
    withErroredAgent(async () => {
      const res = await app.request(`${AGENT_BASE}/cracker/check-update`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          authorization: `Bearer ${errorAgentToken()}`,
        },
        body: JSON.stringify({
          engine: 'hashcat',
          platform: 'linux-x64',
          version: '6.2.7',
        }),
      })
      await expectAgentAuthInvalid(res)
    })
  )

  it(
    'STILL ACCEPTS errored agents on POST /heartbeat (recovery middleware)',
    withErroredAgent(async () => {
      // Positive counterpart to the strict-rejection block above:
      // /heartbeat is the one route that uses
      // requireAgentTokenForHeartbeatRecovery (lenient) so an agent
      // forced into status='error' by a prior fatal heartbeat can
      // recover. A regression that swapped this middleware to the
      // strict variant would land green on the four routes above and
      // only surface as a runtime failure when a fielded agent in
      // error state tried to recover. This test guards against that.
      const res = await app.request(`${AGENT_BASE}/heartbeat`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          authorization: `Bearer ${errorAgentToken()}`,
        },
        body: JSON.stringify({ status: 'online' }),
      })
      expect(res.status).toBe(200)
      const body = (await res.json()) as Record<string, unknown>
      expect(body['acknowledged']).toBe(true)
    })
  )
})

// ─── ZapResponse wire shape regression test (post-U6 fix) ───────────
//
// U6 initially declared ZapResponse as `{ taskId, hashes }` while
// `getZapsForTask` actually returns `{ zaps, hasMore }`. The fix
// restored the original `{ zaps, hasMore }` schema. This test pins
// the contract against the real service mock so the wire shape and
// the spec can never silently diverge again.

describe('Agent API: POST /tasks/:id/report — wire shape', () => {
  it('returns bare { acknowledged: true } body on the non-failure path', async () => {
    // Arrange — default updateTaskProgress mock already returns the
    // {task} success branch; route is supposed to emit the bare
    // taskReportAckSchema body (no `retried` field).
    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/tasks/42/report`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ status: 'running' }),
    })

    expect(res.status).toBe(200)
    const body = (await res.json()) as Record<string, unknown>
    expect(body['acknowledged']).toBe(true)
    // Negative-shape assertion: the bug PR #190 originally shipped had
    // `retried: false` on the non-failure path, breaking consumers with
    // `disallowUnknownFields`. The retried key MUST only appear on the
    // failure-retry branch — pin its absence on the bare-success path.
    expect(body['retried']).toBeUndefined()
  })
})

describe('Agent API: GET /tasks/:id/zaps — wire shape', () => {
  it('returns { zaps, hasMore } body matching getZapsForTask runtime shape', async () => {
    // Arrange — override the default mock with a non-empty payload so
    // the field-shape assertion has actual data to verify.
    const tasksMod = await import('../../src/services/tasks.js')
    ;(
      tasksMod.getZapsForTask as unknown as {
        mockImplementationOnce: (fn: () => unknown) => void
      }
    ).mockImplementationOnce(() => Promise.resolve({ zaps: ['hash1', 'hash2'], hasMore: false }))

    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/tasks/42/zaps`, {
      method: 'GET',
      headers: { authorization: `Bearer ${token}` },
    })

    expect(res.status).toBe(200)
    const body = (await res.json()) as Record<string, unknown>
    expect(body).toHaveProperty('zaps')
    expect(body).toHaveProperty('hasMore')
    expect(Array.isArray(body['zaps'])).toBe(true)
    expect(body['hasMore']).toBe(false)
    // Negative-shape assertions catch a regression that would re-add
    // the wrong keys (`taskId`/`hashes`) and silently break agent
    // codegen consumers parsing this response.
    expect(body['taskId']).toBeUndefined()
    expect(body['hashes']).toBeUndefined()
  })
})

// ─── GET /resources/:type/:id/download-url — param validation ───────
//
// `resourceParamSchema` was widened from `z.string()` to a closed
// `z.enum(['hash-lists', 'wordlists', 'rulelists', 'masklists'])`
// after the route-as-spec migration, and `id` got a MAX_PG_INT4 upper
// bound. Both changes turn what was a downstream 404 (unknown type) or
// 500 (id too large for the int4 column) into a clean 400
// VALIDATION_ERROR at the validator boundary so agents can discover
// the supported `type` vocabulary from the spec and so absurd `id`
// values can't reach the database.

describe('Agent API: GET /resources/:type/:id/download-url — param validation', () => {
  it('rejects unknown resource type with 400 + VALIDATION_ERROR', async () => {
    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/resources/widgets/1/download-url`, {
      method: 'GET',
      headers: { authorization: `Bearer ${token}` },
    })
    expect(res.status).toBe(400)
    await expectAgentValidationError(res)
  })

  it('rejects resource id above PostgreSQL int4 max with 400 + VALIDATION_ERROR', async () => {
    const token = agentToken(TEST_AGENT_TOKEN)
    const res = await app.request(`${AGENT_BASE}/resources/wordlists/2147483648/download-url`, {
      method: 'GET',
      headers: { authorization: `Bearer ${token}` },
    })
    expect(res.status).toBe(400)
    await expectAgentValidationError(res)
  })
})
