/**
 * Enrollment token generation, parsing, and verification.
 *
 * Enrollment tokens are the short, human-typeable credential an admin
 * mints in the dashboard and hands to a new agent. The agent presents it
 * once at `POST /api/v1/agent/enroll`; the server validates + consumes it
 * and issues the agent its long-lived per-agent bearer token (the
 * `agt_<id>_<random>` credential — see `agent-token.ts`). The human never
 * types the bearer token.
 *
 * Format: `etk_<tokenId>_<word-phrase>` where:
 * - `etk` (enrollment token) is the format discriminator.
 * - `<tokenId>` is the `enrollment_tokens.id` routing hint so the server
 *   can fetch the row in O(1) before verifying. An unknown id matches no
 *   row and triggers NO bcrypt verify, so unauthenticated junk cannot burn
 *   CPU. Trust flows from the bcrypt verify, never from the id.
 * - `<word-phrase>` is a memorable diceware-style secret (e.g.
 *   `brave-coral-otter-47`) generated by `unique-names-generator`.
 *
 * Example: `etk_7_brave-coral-otter-47`.
 *
 * **Entropy is intentionally modest (~31 bits).** Enrollment tokens are
 * ephemeral, usage-bounded (one-time or capped reusable), time-bounded
 * (optional expiry), revocable, and project-scoped — so they do not need
 * to be highly crypto-secure, and human typeability is the priority. The
 * word phrase is sourced from `unique-names-generator` (which uses a
 * non-CSPRNG internally — acceptable for this threat model). Only the
 * bcrypt hash of the secret is persisted; the raw token is shown to the
 * operator exactly once at mint time and never stored.
 *
 * Mirrors the `agent-token.ts` / `api-key.ts` shape so the credential
 * surfaces don't drift.
 */
import {
  animals,
  colors,
  adjectives,
  NumberDictionary,
  uniqueNamesGenerator,
} from 'unique-names-generator'

import { logger } from '../config/logger.js'

/**
 * Bcrypt cost factor for stored enrollment-token hashes. Matches the
 * agent-token and Control API key cost (12) so no credential surface is
 * the weak link. Kept as a local constant — mirroring `agent-token.ts` —
 * rather than imported, so a change to one surface is a deliberate,
 * reviewable edit here too.
 */
export const ENROLLMENT_TOKEN_BCRYPT_COST = 12

export const ENROLLMENT_TOKEN_PREFIX = 'etk' as const

/**
 * Word count and dictionaries for the secret phrase. adjectives (1202) ×
 * colors (52) × animals (355) × two-digit number (90) ≈ 2.0e9 ≈ 31 bits.
 * If the entropy budget ever changes, change it here — this is the single
 * source of truth and the test asserts the shape against it.
 */
const NUMBER_DICTIONARY = NumberDictionary.generate({ min: 10, max: 99 })
const SECRET_DICTIONARIES = [adjectives, colors, animals, NUMBER_DICTIONARY]

export interface ParsedEnrollmentToken {
  tokenId: number
  /** The word-phrase secret portion (the part after `etk_<id>_`). */
  secret: string
}

export interface IssuedEnrollmentToken {
  /** Raw token to deliver to the operator exactly once. Never persisted. */
  token: string
  /** Bcrypt hash of the secret to persist in `enrollment_tokens.secret_hash`. */
  hash: string
}

/**
 * Issue a new enrollment token for the given `enrollment_tokens` row id.
 * The row must already exist (insert first to obtain the id, then call
 * this and store the returned hash) — the id is embedded as the routing
 * hint, mirroring how `generateAgentToken(agentId)` requires the agent
 * row to exist first.
 */
export async function generateEnrollmentToken(tokenId: number): Promise<IssuedEnrollmentToken> {
  const secret = uniqueNamesGenerator({
    dictionaries: SECRET_DICTIONARIES,
    length: SECRET_DICTIONARIES.length,
    separator: '-',
    style: 'lowerCase',
  })
  const token = `${ENROLLMENT_TOKEN_PREFIX}_${tokenId}_${secret}`
  const hash = await Bun.password.hash(secret, {
    algorithm: 'bcrypt',
    cost: ENROLLMENT_TOKEN_BCRYPT_COST,
  })
  return { token, hash }
}

/**
 * Strict parse of an enrollment token. Returns null on any deviation from
 * the canonical `etk_<positive-int>_<non-empty>` shape so callers do not
 * have to defend against malformed input downstream. A null return means
 * "this is not a well-formed enrollment token" — not "auth failed".
 *
 * Mirrors `parseApiKey` / `parseAgentToken`: split on the first two `_`
 * separators. The word-phrase secret uses `-` internally, so it never
 * collides with the `_` structural separators.
 */
export function parseEnrollmentToken(token: string): ParsedEnrollmentToken | null {
  if (!token) return null
  const firstSep = token.indexOf('_')
  if (firstSep <= 0) return null
  const secondSep = token.indexOf('_', firstSep + 1)
  if (secondSep <= firstSep + 1) return null
  const prefix = token.slice(0, firstSep)
  const tokenIdRaw = token.slice(firstSep + 1, secondSep)
  const secret = token.slice(secondSep + 1)
  if (prefix !== ENROLLMENT_TOKEN_PREFIX) return null
  if (!secret) return null
  if (!/^[1-9]\d*$/.test(tokenIdRaw)) return null
  const tokenId = Number(tokenIdRaw)
  // Reject ids that lose precision in double-precision FP — the value
  // beyond Number.MAX_SAFE_INTEGER is no longer what the client sent, so a
  // strict-equals lookup against the row id would silently match nothing
  // (or, worse, the wrong row).
  if (!Number.isInteger(tokenId) || tokenId <= 0 || tokenId > Number.MAX_SAFE_INTEGER) {
    return null
  }
  return { tokenId, secret }
}

/**
 * Constant-time verify of a raw secret against its stored bcrypt hash.
 * Returns false on any malformed input rather than throwing — the caller
 * treats a false return as "deny" without distinguishing the failure mode
 * (enrollment rejections are uniform by design). A real bcrypt failure
 * (corrupt hash, runtime error) is logged so an opaque deny does not eat
 * operational signal.
 */
export async function verifyEnrollmentTokenHash(secret: string, hash: string): Promise<boolean> {
  if (!secret || !hash) return false
  try {
    return await Bun.password.verify(secret, hash)
  } catch (err) {
    // error, not warn: a throw here means a corrupt stored hash or a runtime
    // fault (a normal mismatch returns false), which needs investigation and
    // should reach error-level alerting rather than be filtered as noise.
    logger.error({ err }, 'Bun.password.verify threw for enrollment token — treating as failure')
    return false
  }
}
