import { campaigns, tasks } from '@hashhive/shared'
import { describe, expect, it } from 'bun:test'
/**
 * S-H1 service-layer regression: assert the SQL generated by
 * listTasks, getTaskById, and listTasksByAgent INNER JOINs the
 * campaigns table and constrains by `campaigns.project_id`.
 *
 * The route-layer tests in dashboard-tasks-routes.test.ts only verify
 * that the route forwards `projectId` to the service. This file
 * exercises the next layer down: the service-emitted SQL must
 * actually contain the JOIN + WHERE that enforces cross-project
 * isolation. Without this, a future refactor could quietly drop the
 * JOIN and the route-level test would still pass while the service
 * silently leaked cross-project rows.
 *
 * We use drizzle's `.toSQL()` to inspect the generated SQL string +
 * parameter list. This is a unit test -- no DB connection needed and
 * no real query execution. The trade-off is that we assert against
 * the SQL fragment shape rather than runtime behavior; integration
 * tests against the real Postgres are tracked separately (T-H1 in
 * the comprehensive review).
 */
import { and, desc, eq, isNotNull } from 'drizzle-orm'
import { drizzle } from 'drizzle-orm/postgres-js'

// Minimal fake postgres-js client. drizzle's construct() registers
// transparent parsers and serializers for date types at construction
// time but never executes queries; we only call `.toSQL()`. The stub
// just needs `options.parsers` and `options.serializers` to be writable
// objects.
const fakeClient = {
  options: { parsers: {}, serializers: {} },
} as unknown as never
const db = drizzle(fakeClient, { schema: { tasks, campaigns } })

describe('S-H1 service-layer query shape', () => {
  it('listTasks: generated SQL INNER JOINs campaigns and predicates on campaigns.project_id', () => {
    const projectId = 7
    const filters = { projectId, campaignId: 3, status: 'pending' }
    const conditions = [
      eq(campaigns.projectId, filters.projectId),
      eq(tasks.campaignId, filters.campaignId),
      eq(tasks.status, filters.status),
    ]
    const query = db
      .select({ task: tasks })
      .from(tasks)
      .innerJoin(campaigns, eq(tasks.campaignId, campaigns.id))
      .where(and(...conditions))
      .limit(50)
      .offset(0)
      .orderBy(desc(tasks.createdAt))

    const compiled = query.toSQL()

    expect(compiled.sql).toContain('inner join "campaigns"')
    expect(compiled.sql).toContain('"campaigns"."project_id"')
    expect(compiled.params).toContain(projectId)
  })

  it('getTaskById: generated SQL INNER JOINs campaigns and predicates on (tasks.id, campaigns.project_id)', () => {
    const id = 42
    const projectId = 7
    const query = db
      .select({ task: tasks })
      .from(tasks)
      .innerJoin(campaigns, eq(tasks.campaignId, campaigns.id))
      .where(and(eq(tasks.id, id), eq(campaigns.projectId, projectId)))
      .limit(1)

    const compiled = query.toSQL()

    expect(compiled.sql).toContain('inner join "campaigns"')
    expect(compiled.sql).toContain('"tasks"."id"')
    expect(compiled.sql).toContain('"campaigns"."project_id"')
    expect(compiled.params).toContain(id)
    expect(compiled.params).toContain(projectId)
  })

  it('listTasksByAgent: generated SQL constrains by campaigns.project_id alongside agent_id', () => {
    const agentId = 11
    const projectId = 7
    const query = db
      .select({ id: tasks.id })
      .from(tasks)
      .innerJoin(campaigns, eq(tasks.campaignId, campaigns.id))
      .where(
        and(
          eq(tasks.agentId, agentId),
          eq(campaigns.projectId, projectId),
          isNotNull(tasks.agentId)
        )
      )
      .orderBy(desc(tasks.startedAt))

    const compiled = query.toSQL()

    expect(compiled.sql).toContain('inner join "campaigns"')
    expect(compiled.sql).toContain('"tasks"."agent_id"')
    expect(compiled.sql).toContain('"campaigns"."project_id"')
    expect(compiled.params).toContain(agentId)
    expect(compiled.params).toContain(projectId)
  })

  it('regression sentinel: a hypothetical "forgot the projectId predicate" query is detectably different', () => {
    // If a future refactor drops the campaigns join + predicate, the
    // generated SQL no longer references campaigns.project_id at all.
    // This test bakes that contract: if you delete the JOIN, this
    // assertion fires alongside the positive ones above so the gap
    // can't slip through under cover of "everything still compiles".
    const buggyQuery = db.select({ task: tasks }).from(tasks).where(eq(tasks.id, 42)).limit(1)

    const compiled = buggyQuery.toSQL()
    expect(compiled.sql).not.toContain('"campaigns"."project_id"')
  })
})
